package aka.convertor.json.exceptions;

import org.eclipse.jdt.annotation.NonNull;

/**
 * Base class for all exceptions generated by the Json convertor engine. 
 * 
 * @author Welle Charlotte
 */
public final class JSONException extends Exception {

	private static final long serialVersionUID = 6512028366036130577L;
	private final long byteOffset;
	private final long charOffset;
	private final int lineNumber;
	private final int columnNumber;

	/**
	 * Constructor.
	 * 
	 * @param message error message
	 * @param byteOffset byte offset of the error
	 * @param charOffset char offset of the error
	 * @param lineNumber line number of the error
	 * @param columnNumber column number of the error
	 */
	/**
	 * @param message
	 * @param byteOffset
	 * @param charOffset
	 * @param lineNumber
	 * @param columnNumber
	 */
	public JSONException(@NonNull final String message, final long byteOffset, final long charOffset, final int lineNumber, final int columnNumber) {
		super(message);
		this.byteOffset = byteOffset;
		this.charOffset = charOffset;
		this.lineNumber = lineNumber;
		this.columnNumber = columnNumber;
	}

	/**
	 * Get the byte offset of the error.
	 * 
	 * @return the byteOffset
	 */
	public long getByteOffset() {
		return this.byteOffset;
	}

	/**
	 * Get the char offset of the error.
	 * 
	 * @return the charOffset
	 */
	public long getCharOffset() {
		return this.charOffset;
	}

	/**
	 * Get the line number of the error.
	 * 
	 * @return the lineNumber
	 */
	public int getLineNumber() {
		return this.lineNumber;
	}

	/**
	 * Get the column number of the error.
	 * 
	 * @return the columnNumber
	 */
	public int getColumnNumber() {
		return this.columnNumber;
	}
}
