package aka.convertor.examples.example2;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class Example2 {

    @SerializedName("web-app")
    private WebApp webApp;

    /**
     * Get value of webApp 
     *
     * @return WebApp value of webApp
     */
    public WebApp getWebApp() {
       return this.webApp;
    }
}
