package aka.convertor.examples.example2;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class Example2 {

    @JsonProperty("web-app")
    private WebApp webApp;

    /**
     * Filling Constructor
     *
     * @param webApp WebApp
     */
    public Example2(final WebApp webApp) {
        this.webApp = webApp;
    }
    
    /**
     * Get value of webApp
     *
     * @return WebApp value of webApp
     */
    public final WebApp getWebApp() {
        return this.webApp;
    }

    
    /**
     * Set value of webApp
     *
     * @param webApp
     */
    public final void setWebApp(final WebApp webApp) {
        this.webApp = webApp;
    }
}