package aka.convertor.examples.example2;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class InitParam {

    private Integer cachePackageTagsTrack;
    @JsonProperty("configGlossary:staticPath")
    private String configGlossaryStaticPath;
    @JsonProperty("configGlossary:installationAt")
    private String configGlossaryInstallationAt;
    private Integer cacheTemplatesTrack;
    @JsonProperty("configGlossary:poweredBy")
    private String configGlossaryPoweredBy;
    private String searchEngineFileTemplate;
    private String templateProcessorClass;
    private String searchEngineListTemplate;
    private Boolean useDataStore;
    private Boolean betaServer;
    private String templateLoaderClass;
    private String searchEngineRobotsDb;
    private String logLocation;
    private String mailHost;
    private Integer cachePackageTagsRefresh;
    private String dataStoreLogLevel;
    private String fileTransferFolder;
    private String dataStoreTestQuery;
    private Integer lookInContext;
    private Integer dataStoreMaxConns;
    private String dataStoreName;
    private String templateOverridePath;
    private String dataStoreLogFile;
    private Integer dataStoreInitConns;
    private Integer dataLog;
    private String redirectionClass;
    private String jspFileTemplate;
    private Integer cacheTemplatesRefresh;
    private String dataStorePassword;
    private String dataStoreClass;
    private Integer log;
    private String defaultFileTemplate;
    private String dataLogLocation;
    @JsonProperty("configGlossary:adminEmail")
    private String configGlossaryAdminEmail;
    private Integer cachePagesStore;
    @JsonProperty("configGlossary:poweredByIcon")
    private String configGlossaryPoweredByIcon;
    private Integer cachePagesTrack;
    private Integer cachePagesDirtyRead;
    private String dataLogMaxSize;
    private Integer cachePackageTagsStore;
    private String mailHostOverride;
    private Integer dataStoreConnUsageLimit;
    private String logMaxSize;
    private Boolean useJSP;
    private String dataStoreUrl;
    private String templatePath;
    private Integer cacheTemplatesStore;
    private String removeTemplateCache;
    private String jspListTemplate;
    private String removePageCache;
    private Integer adminGroupID;
    private Integer maxUrlLength;
    private Integer cachePagesRefresh;
    private String dataStoreDriver;
    private String dataStoreUser;
    private String defaultListTemplate;

    /**
     * Filling Constructor
     *
     * @param cachePackageTagsTrack Integer
     * @param configGlossaryStaticPath String
     * @param configGlossaryInstallationAt String
     * @param cacheTemplatesTrack Integer
     * @param configGlossaryPoweredBy String
     * @param searchEngineFileTemplate String
     * @param templateProcessorClass String
     * @param searchEngineListTemplate String
     * @param useDataStore Boolean
     * @param betaServer Boolean
     * @param templateLoaderClass String
     * @param searchEngineRobotsDb String
     * @param logLocation String
     * @param mailHost String
     * @param cachePackageTagsRefresh Integer
     * @param dataStoreLogLevel String
     * @param fileTransferFolder String
     * @param dataStoreTestQuery String
     * @param lookInContext Integer
     * @param dataStoreMaxConns Integer
     * @param dataStoreName String
     * @param templateOverridePath String
     * @param dataStoreLogFile String
     * @param dataStoreInitConns Integer
     * @param dataLog Integer
     * @param redirectionClass String
     * @param jspFileTemplate String
     * @param cacheTemplatesRefresh Integer
     * @param dataStorePassword String
     * @param dataStoreClass String
     * @param log Integer
     * @param defaultFileTemplate String
     * @param dataLogLocation String
     * @param configGlossaryAdminEmail String
     * @param cachePagesStore Integer
     * @param configGlossaryPoweredByIcon String
     * @param cachePagesTrack Integer
     * @param cachePagesDirtyRead Integer
     * @param dataLogMaxSize String
     * @param cachePackageTagsStore Integer
     * @param mailHostOverride String
     * @param dataStoreConnUsageLimit Integer
     * @param logMaxSize String
     * @param useJSP Boolean
     * @param dataStoreUrl String
     * @param templatePath String
     * @param cacheTemplatesStore Integer
     * @param removeTemplateCache String
     * @param jspListTemplate String
     * @param removePageCache String
     * @param adminGroupID Integer
     * @param maxUrlLength Integer
     * @param cachePagesRefresh Integer
     * @param dataStoreDriver String
     * @param dataStoreUser String
     * @param defaultListTemplate String
     */
    public InitParam(final Integer cachePackageTagsTrack, final String configGlossaryStaticPath, final String configGlossaryInstallationAt, final Integer cacheTemplatesTrack, final String configGlossaryPoweredBy, final String searchEngineFileTemplate, final String templateProcessorClass, final String searchEngineListTemplate, final Boolean useDataStore, final Boolean betaServer, final String templateLoaderClass, final String searchEngineRobotsDb, final String logLocation, final String mailHost, final Integer cachePackageTagsRefresh, final String dataStoreLogLevel, final String fileTransferFolder, final String dataStoreTestQuery, final Integer lookInContext, final Integer dataStoreMaxConns, final String dataStoreName, final String templateOverridePath, final String dataStoreLogFile, final Integer dataStoreInitConns, final Integer dataLog, final String redirectionClass, final String jspFileTemplate, final Integer cacheTemplatesRefresh, final String dataStorePassword, final String dataStoreClass, final Integer log, final String defaultFileTemplate, final String dataLogLocation, final String configGlossaryAdminEmail, final Integer cachePagesStore, final String configGlossaryPoweredByIcon, final Integer cachePagesTrack, final Integer cachePagesDirtyRead, final String dataLogMaxSize, final Integer cachePackageTagsStore, final String mailHostOverride, final Integer dataStoreConnUsageLimit, final String logMaxSize, final Boolean useJSP, final String dataStoreUrl, final String templatePath, final Integer cacheTemplatesStore, final String removeTemplateCache, final String jspListTemplate, final String removePageCache, final Integer adminGroupID, final Integer maxUrlLength, final Integer cachePagesRefresh, final String dataStoreDriver, final String dataStoreUser, final String defaultListTemplate) {
        this.cachePackageTagsTrack = cachePackageTagsTrack;
        this.configGlossaryStaticPath = configGlossaryStaticPath;
        this.configGlossaryInstallationAt = configGlossaryInstallationAt;
        this.cacheTemplatesTrack = cacheTemplatesTrack;
        this.configGlossaryPoweredBy = configGlossaryPoweredBy;
        this.searchEngineFileTemplate = searchEngineFileTemplate;
        this.templateProcessorClass = templateProcessorClass;
        this.searchEngineListTemplate = searchEngineListTemplate;
        this.useDataStore = useDataStore;
        this.betaServer = betaServer;
        this.templateLoaderClass = templateLoaderClass;
        this.searchEngineRobotsDb = searchEngineRobotsDb;
        this.logLocation = logLocation;
        this.mailHost = mailHost;
        this.cachePackageTagsRefresh = cachePackageTagsRefresh;
        this.dataStoreLogLevel = dataStoreLogLevel;
        this.fileTransferFolder = fileTransferFolder;
        this.dataStoreTestQuery = dataStoreTestQuery;
        this.lookInContext = lookInContext;
        this.dataStoreMaxConns = dataStoreMaxConns;
        this.dataStoreName = dataStoreName;
        this.templateOverridePath = templateOverridePath;
        this.dataStoreLogFile = dataStoreLogFile;
        this.dataStoreInitConns = dataStoreInitConns;
        this.dataLog = dataLog;
        this.redirectionClass = redirectionClass;
        this.jspFileTemplate = jspFileTemplate;
        this.cacheTemplatesRefresh = cacheTemplatesRefresh;
        this.dataStorePassword = dataStorePassword;
        this.dataStoreClass = dataStoreClass;
        this.log = log;
        this.defaultFileTemplate = defaultFileTemplate;
        this.dataLogLocation = dataLogLocation;
        this.configGlossaryAdminEmail = configGlossaryAdminEmail;
        this.cachePagesStore = cachePagesStore;
        this.configGlossaryPoweredByIcon = configGlossaryPoweredByIcon;
        this.cachePagesTrack = cachePagesTrack;
        this.cachePagesDirtyRead = cachePagesDirtyRead;
        this.dataLogMaxSize = dataLogMaxSize;
        this.cachePackageTagsStore = cachePackageTagsStore;
        this.mailHostOverride = mailHostOverride;
        this.dataStoreConnUsageLimit = dataStoreConnUsageLimit;
        this.logMaxSize = logMaxSize;
        this.useJSP = useJSP;
        this.dataStoreUrl = dataStoreUrl;
        this.templatePath = templatePath;
        this.cacheTemplatesStore = cacheTemplatesStore;
        this.removeTemplateCache = removeTemplateCache;
        this.jspListTemplate = jspListTemplate;
        this.removePageCache = removePageCache;
        this.adminGroupID = adminGroupID;
        this.maxUrlLength = maxUrlLength;
        this.cachePagesRefresh = cachePagesRefresh;
        this.dataStoreDriver = dataStoreDriver;
        this.dataStoreUser = dataStoreUser;
        this.defaultListTemplate = defaultListTemplate;
    }
    
    /**
     * Get value of cachePackageTagsTrack
     *
     * @return Integer value of cachePackageTagsTrack
     */
    public final Integer getCachePackageTagsTrack() {
        return this.cachePackageTagsTrack;
    }
    
    /**
     * Get value of configGlossaryStaticPath
     *
     * @return String value of configGlossaryStaticPath
     */
    public final String getConfigGlossaryStaticPath() {
        return this.configGlossaryStaticPath;
    }
    
    /**
     * Get value of configGlossaryInstallationAt
     *
     * @return String value of configGlossaryInstallationAt
     */
    public final String getConfigGlossaryInstallationAt() {
        return this.configGlossaryInstallationAt;
    }
    
    /**
     * Get value of cacheTemplatesTrack
     *
     * @return Integer value of cacheTemplatesTrack
     */
    public final Integer getCacheTemplatesTrack() {
        return this.cacheTemplatesTrack;
    }
    
    /**
     * Get value of configGlossaryPoweredBy
     *
     * @return String value of configGlossaryPoweredBy
     */
    public final String getConfigGlossaryPoweredBy() {
        return this.configGlossaryPoweredBy;
    }
    
    /**
     * Get value of searchEngineFileTemplate
     *
     * @return String value of searchEngineFileTemplate
     */
    public final String getSearchEngineFileTemplate() {
        return this.searchEngineFileTemplate;
    }
    
    /**
     * Get value of templateProcessorClass
     *
     * @return String value of templateProcessorClass
     */
    public final String getTemplateProcessorClass() {
        return this.templateProcessorClass;
    }
    
    /**
     * Get value of searchEngineListTemplate
     *
     * @return String value of searchEngineListTemplate
     */
    public final String getSearchEngineListTemplate() {
        return this.searchEngineListTemplate;
    }
    
    /**
     * Get value of useDataStore
     *
     * @return Boolean value of useDataStore
     */
    public final Boolean getUseDataStore() {
        return this.useDataStore;
    }
    
    /**
     * Get value of betaServer
     *
     * @return Boolean value of betaServer
     */
    public final Boolean getBetaServer() {
        return this.betaServer;
    }
    
    /**
     * Get value of templateLoaderClass
     *
     * @return String value of templateLoaderClass
     */
    public final String getTemplateLoaderClass() {
        return this.templateLoaderClass;
    }
    
    /**
     * Get value of searchEngineRobotsDb
     *
     * @return String value of searchEngineRobotsDb
     */
    public final String getSearchEngineRobotsDb() {
        return this.searchEngineRobotsDb;
    }
    
    /**
     * Get value of logLocation
     *
     * @return String value of logLocation
     */
    public final String getLogLocation() {
        return this.logLocation;
    }
    
    /**
     * Get value of mailHost
     *
     * @return String value of mailHost
     */
    public final String getMailHost() {
        return this.mailHost;
    }
    
    /**
     * Get value of cachePackageTagsRefresh
     *
     * @return Integer value of cachePackageTagsRefresh
     */
    public final Integer getCachePackageTagsRefresh() {
        return this.cachePackageTagsRefresh;
    }
    
    /**
     * Get value of dataStoreLogLevel
     *
     * @return String value of dataStoreLogLevel
     */
    public final String getDataStoreLogLevel() {
        return this.dataStoreLogLevel;
    }
    
    /**
     * Get value of fileTransferFolder
     *
     * @return String value of fileTransferFolder
     */
    public final String getFileTransferFolder() {
        return this.fileTransferFolder;
    }
    
    /**
     * Get value of dataStoreTestQuery
     *
     * @return String value of dataStoreTestQuery
     */
    public final String getDataStoreTestQuery() {
        return this.dataStoreTestQuery;
    }
    
    /**
     * Get value of lookInContext
     *
     * @return Integer value of lookInContext
     */
    public final Integer getLookInContext() {
        return this.lookInContext;
    }
    
    /**
     * Get value of dataStoreMaxConns
     *
     * @return Integer value of dataStoreMaxConns
     */
    public final Integer getDataStoreMaxConns() {
        return this.dataStoreMaxConns;
    }
    
    /**
     * Get value of dataStoreName
     *
     * @return String value of dataStoreName
     */
    public final String getDataStoreName() {
        return this.dataStoreName;
    }
    
    /**
     * Get value of templateOverridePath
     *
     * @return String value of templateOverridePath
     */
    public final String getTemplateOverridePath() {
        return this.templateOverridePath;
    }
    
    /**
     * Get value of dataStoreLogFile
     *
     * @return String value of dataStoreLogFile
     */
    public final String getDataStoreLogFile() {
        return this.dataStoreLogFile;
    }
    
    /**
     * Get value of dataStoreInitConns
     *
     * @return Integer value of dataStoreInitConns
     */
    public final Integer getDataStoreInitConns() {
        return this.dataStoreInitConns;
    }
    
    /**
     * Get value of dataLog
     *
     * @return Integer value of dataLog
     */
    public final Integer getDataLog() {
        return this.dataLog;
    }
    
    /**
     * Get value of redirectionClass
     *
     * @return String value of redirectionClass
     */
    public final String getRedirectionClass() {
        return this.redirectionClass;
    }
    
    /**
     * Get value of jspFileTemplate
     *
     * @return String value of jspFileTemplate
     */
    public final String getJspFileTemplate() {
        return this.jspFileTemplate;
    }
    
    /**
     * Get value of cacheTemplatesRefresh
     *
     * @return Integer value of cacheTemplatesRefresh
     */
    public final Integer getCacheTemplatesRefresh() {
        return this.cacheTemplatesRefresh;
    }
    
    /**
     * Get value of dataStorePassword
     *
     * @return String value of dataStorePassword
     */
    public final String getDataStorePassword() {
        return this.dataStorePassword;
    }
    
    /**
     * Get value of dataStoreClass
     *
     * @return String value of dataStoreClass
     */
    public final String getDataStoreClass() {
        return this.dataStoreClass;
    }
    
    /**
     * Get value of log
     *
     * @return Integer value of log
     */
    public final Integer getLog() {
        return this.log;
    }
    
    /**
     * Get value of defaultFileTemplate
     *
     * @return String value of defaultFileTemplate
     */
    public final String getDefaultFileTemplate() {
        return this.defaultFileTemplate;
    }
    
    /**
     * Get value of dataLogLocation
     *
     * @return String value of dataLogLocation
     */
    public final String getDataLogLocation() {
        return this.dataLogLocation;
    }
    
    /**
     * Get value of configGlossaryAdminEmail
     *
     * @return String value of configGlossaryAdminEmail
     */
    public final String getConfigGlossaryAdminEmail() {
        return this.configGlossaryAdminEmail;
    }
    
    /**
     * Get value of cachePagesStore
     *
     * @return Integer value of cachePagesStore
     */
    public final Integer getCachePagesStore() {
        return this.cachePagesStore;
    }
    
    /**
     * Get value of configGlossaryPoweredByIcon
     *
     * @return String value of configGlossaryPoweredByIcon
     */
    public final String getConfigGlossaryPoweredByIcon() {
        return this.configGlossaryPoweredByIcon;
    }
    
    /**
     * Get value of cachePagesTrack
     *
     * @return Integer value of cachePagesTrack
     */
    public final Integer getCachePagesTrack() {
        return this.cachePagesTrack;
    }
    
    /**
     * Get value of cachePagesDirtyRead
     *
     * @return Integer value of cachePagesDirtyRead
     */
    public final Integer getCachePagesDirtyRead() {
        return this.cachePagesDirtyRead;
    }
    
    /**
     * Get value of dataLogMaxSize
     *
     * @return String value of dataLogMaxSize
     */
    public final String getDataLogMaxSize() {
        return this.dataLogMaxSize;
    }
    
    /**
     * Get value of cachePackageTagsStore
     *
     * @return Integer value of cachePackageTagsStore
     */
    public final Integer getCachePackageTagsStore() {
        return this.cachePackageTagsStore;
    }
    
    /**
     * Get value of mailHostOverride
     *
     * @return String value of mailHostOverride
     */
    public final String getMailHostOverride() {
        return this.mailHostOverride;
    }
    
    /**
     * Get value of dataStoreConnUsageLimit
     *
     * @return Integer value of dataStoreConnUsageLimit
     */
    public final Integer getDataStoreConnUsageLimit() {
        return this.dataStoreConnUsageLimit;
    }
    
    /**
     * Get value of logMaxSize
     *
     * @return String value of logMaxSize
     */
    public final String getLogMaxSize() {
        return this.logMaxSize;
    }
    
    /**
     * Get value of useJSP
     *
     * @return Boolean value of useJSP
     */
    public final Boolean getUseJSP() {
        return this.useJSP;
    }
    
    /**
     * Get value of dataStoreUrl
     *
     * @return String value of dataStoreUrl
     */
    public final String getDataStoreUrl() {
        return this.dataStoreUrl;
    }
    
    /**
     * Get value of templatePath
     *
     * @return String value of templatePath
     */
    public final String getTemplatePath() {
        return this.templatePath;
    }
    
    /**
     * Get value of cacheTemplatesStore
     *
     * @return Integer value of cacheTemplatesStore
     */
    public final Integer getCacheTemplatesStore() {
        return this.cacheTemplatesStore;
    }
    
    /**
     * Get value of removeTemplateCache
     *
     * @return String value of removeTemplateCache
     */
    public final String getRemoveTemplateCache() {
        return this.removeTemplateCache;
    }
    
    /**
     * Get value of jspListTemplate
     *
     * @return String value of jspListTemplate
     */
    public final String getJspListTemplate() {
        return this.jspListTemplate;
    }
    
    /**
     * Get value of removePageCache
     *
     * @return String value of removePageCache
     */
    public final String getRemovePageCache() {
        return this.removePageCache;
    }
    
    /**
     * Get value of adminGroupID
     *
     * @return Integer value of adminGroupID
     */
    public final Integer getAdminGroupID() {
        return this.adminGroupID;
    }
    
    /**
     * Get value of maxUrlLength
     *
     * @return Integer value of maxUrlLength
     */
    public final Integer getMaxUrlLength() {
        return this.maxUrlLength;
    }
    
    /**
     * Get value of cachePagesRefresh
     *
     * @return Integer value of cachePagesRefresh
     */
    public final Integer getCachePagesRefresh() {
        return this.cachePagesRefresh;
    }
    
    /**
     * Get value of dataStoreDriver
     *
     * @return String value of dataStoreDriver
     */
    public final String getDataStoreDriver() {
        return this.dataStoreDriver;
    }
    
    /**
     * Get value of dataStoreUser
     *
     * @return String value of dataStoreUser
     */
    public final String getDataStoreUser() {
        return this.dataStoreUser;
    }
    
    /**
     * Get value of defaultListTemplate
     *
     * @return String value of defaultListTemplate
     */
    public final String getDefaultListTemplate() {
        return this.defaultListTemplate;
    }

    
    /**
     * Set value of cachePackageTagsTrack
     *
     * @param cachePackageTagsTrack
     */
    public final void setCachePackageTagsTrack(final Integer cachePackageTagsTrack) {
        this.cachePackageTagsTrack = cachePackageTagsTrack;
    }
    
    /**
     * Set value of configGlossaryStaticPath
     *
     * @param configGlossaryStaticPath
     */
    public final void setConfigGlossaryStaticPath(final String configGlossaryStaticPath) {
        this.configGlossaryStaticPath = configGlossaryStaticPath;
    }
    
    /**
     * Set value of configGlossaryInstallationAt
     *
     * @param configGlossaryInstallationAt
     */
    public final void setConfigGlossaryInstallationAt(final String configGlossaryInstallationAt) {
        this.configGlossaryInstallationAt = configGlossaryInstallationAt;
    }
    
    /**
     * Set value of cacheTemplatesTrack
     *
     * @param cacheTemplatesTrack
     */
    public final void setCacheTemplatesTrack(final Integer cacheTemplatesTrack) {
        this.cacheTemplatesTrack = cacheTemplatesTrack;
    }
    
    /**
     * Set value of configGlossaryPoweredBy
     *
     * @param configGlossaryPoweredBy
     */
    public final void setConfigGlossaryPoweredBy(final String configGlossaryPoweredBy) {
        this.configGlossaryPoweredBy = configGlossaryPoweredBy;
    }
    
    /**
     * Set value of searchEngineFileTemplate
     *
     * @param searchEngineFileTemplate
     */
    public final void setSearchEngineFileTemplate(final String searchEngineFileTemplate) {
        this.searchEngineFileTemplate = searchEngineFileTemplate;
    }
    
    /**
     * Set value of templateProcessorClass
     *
     * @param templateProcessorClass
     */
    public final void setTemplateProcessorClass(final String templateProcessorClass) {
        this.templateProcessorClass = templateProcessorClass;
    }
    
    /**
     * Set value of searchEngineListTemplate
     *
     * @param searchEngineListTemplate
     */
    public final void setSearchEngineListTemplate(final String searchEngineListTemplate) {
        this.searchEngineListTemplate = searchEngineListTemplate;
    }
    
    /**
     * Set value of useDataStore
     *
     * @param useDataStore
     */
    public final void setUseDataStore(final Boolean useDataStore) {
        this.useDataStore = useDataStore;
    }
    
    /**
     * Set value of betaServer
     *
     * @param betaServer
     */
    public final void setBetaServer(final Boolean betaServer) {
        this.betaServer = betaServer;
    }
    
    /**
     * Set value of templateLoaderClass
     *
     * @param templateLoaderClass
     */
    public final void setTemplateLoaderClass(final String templateLoaderClass) {
        this.templateLoaderClass = templateLoaderClass;
    }
    
    /**
     * Set value of searchEngineRobotsDb
     *
     * @param searchEngineRobotsDb
     */
    public final void setSearchEngineRobotsDb(final String searchEngineRobotsDb) {
        this.searchEngineRobotsDb = searchEngineRobotsDb;
    }
    
    /**
     * Set value of logLocation
     *
     * @param logLocation
     */
    public final void setLogLocation(final String logLocation) {
        this.logLocation = logLocation;
    }
    
    /**
     * Set value of mailHost
     *
     * @param mailHost
     */
    public final void setMailHost(final String mailHost) {
        this.mailHost = mailHost;
    }
    
    /**
     * Set value of cachePackageTagsRefresh
     *
     * @param cachePackageTagsRefresh
     */
    public final void setCachePackageTagsRefresh(final Integer cachePackageTagsRefresh) {
        this.cachePackageTagsRefresh = cachePackageTagsRefresh;
    }
    
    /**
     * Set value of dataStoreLogLevel
     *
     * @param dataStoreLogLevel
     */
    public final void setDataStoreLogLevel(final String dataStoreLogLevel) {
        this.dataStoreLogLevel = dataStoreLogLevel;
    }
    
    /**
     * Set value of fileTransferFolder
     *
     * @param fileTransferFolder
     */
    public final void setFileTransferFolder(final String fileTransferFolder) {
        this.fileTransferFolder = fileTransferFolder;
    }
    
    /**
     * Set value of dataStoreTestQuery
     *
     * @param dataStoreTestQuery
     */
    public final void setDataStoreTestQuery(final String dataStoreTestQuery) {
        this.dataStoreTestQuery = dataStoreTestQuery;
    }
    
    /**
     * Set value of lookInContext
     *
     * @param lookInContext
     */
    public final void setLookInContext(final Integer lookInContext) {
        this.lookInContext = lookInContext;
    }
    
    /**
     * Set value of dataStoreMaxConns
     *
     * @param dataStoreMaxConns
     */
    public final void setDataStoreMaxConns(final Integer dataStoreMaxConns) {
        this.dataStoreMaxConns = dataStoreMaxConns;
    }
    
    /**
     * Set value of dataStoreName
     *
     * @param dataStoreName
     */
    public final void setDataStoreName(final String dataStoreName) {
        this.dataStoreName = dataStoreName;
    }
    
    /**
     * Set value of templateOverridePath
     *
     * @param templateOverridePath
     */
    public final void setTemplateOverridePath(final String templateOverridePath) {
        this.templateOverridePath = templateOverridePath;
    }
    
    /**
     * Set value of dataStoreLogFile
     *
     * @param dataStoreLogFile
     */
    public final void setDataStoreLogFile(final String dataStoreLogFile) {
        this.dataStoreLogFile = dataStoreLogFile;
    }
    
    /**
     * Set value of dataStoreInitConns
     *
     * @param dataStoreInitConns
     */
    public final void setDataStoreInitConns(final Integer dataStoreInitConns) {
        this.dataStoreInitConns = dataStoreInitConns;
    }
    
    /**
     * Set value of dataLog
     *
     * @param dataLog
     */
    public final void setDataLog(final Integer dataLog) {
        this.dataLog = dataLog;
    }
    
    /**
     * Set value of redirectionClass
     *
     * @param redirectionClass
     */
    public final void setRedirectionClass(final String redirectionClass) {
        this.redirectionClass = redirectionClass;
    }
    
    /**
     * Set value of jspFileTemplate
     *
     * @param jspFileTemplate
     */
    public final void setJspFileTemplate(final String jspFileTemplate) {
        this.jspFileTemplate = jspFileTemplate;
    }
    
    /**
     * Set value of cacheTemplatesRefresh
     *
     * @param cacheTemplatesRefresh
     */
    public final void setCacheTemplatesRefresh(final Integer cacheTemplatesRefresh) {
        this.cacheTemplatesRefresh = cacheTemplatesRefresh;
    }
    
    /**
     * Set value of dataStorePassword
     *
     * @param dataStorePassword
     */
    public final void setDataStorePassword(final String dataStorePassword) {
        this.dataStorePassword = dataStorePassword;
    }
    
    /**
     * Set value of dataStoreClass
     *
     * @param dataStoreClass
     */
    public final void setDataStoreClass(final String dataStoreClass) {
        this.dataStoreClass = dataStoreClass;
    }
    
    /**
     * Set value of log
     *
     * @param log
     */
    public final void setLog(final Integer log) {
        this.log = log;
    }
    
    /**
     * Set value of defaultFileTemplate
     *
     * @param defaultFileTemplate
     */
    public final void setDefaultFileTemplate(final String defaultFileTemplate) {
        this.defaultFileTemplate = defaultFileTemplate;
    }
    
    /**
     * Set value of dataLogLocation
     *
     * @param dataLogLocation
     */
    public final void setDataLogLocation(final String dataLogLocation) {
        this.dataLogLocation = dataLogLocation;
    }
    
    /**
     * Set value of configGlossaryAdminEmail
     *
     * @param configGlossaryAdminEmail
     */
    public final void setConfigGlossaryAdminEmail(final String configGlossaryAdminEmail) {
        this.configGlossaryAdminEmail = configGlossaryAdminEmail;
    }
    
    /**
     * Set value of cachePagesStore
     *
     * @param cachePagesStore
     */
    public final void setCachePagesStore(final Integer cachePagesStore) {
        this.cachePagesStore = cachePagesStore;
    }
    
    /**
     * Set value of configGlossaryPoweredByIcon
     *
     * @param configGlossaryPoweredByIcon
     */
    public final void setConfigGlossaryPoweredByIcon(final String configGlossaryPoweredByIcon) {
        this.configGlossaryPoweredByIcon = configGlossaryPoweredByIcon;
    }
    
    /**
     * Set value of cachePagesTrack
     *
     * @param cachePagesTrack
     */
    public final void setCachePagesTrack(final Integer cachePagesTrack) {
        this.cachePagesTrack = cachePagesTrack;
    }
    
    /**
     * Set value of cachePagesDirtyRead
     *
     * @param cachePagesDirtyRead
     */
    public final void setCachePagesDirtyRead(final Integer cachePagesDirtyRead) {
        this.cachePagesDirtyRead = cachePagesDirtyRead;
    }
    
    /**
     * Set value of dataLogMaxSize
     *
     * @param dataLogMaxSize
     */
    public final void setDataLogMaxSize(final String dataLogMaxSize) {
        this.dataLogMaxSize = dataLogMaxSize;
    }
    
    /**
     * Set value of cachePackageTagsStore
     *
     * @param cachePackageTagsStore
     */
    public final void setCachePackageTagsStore(final Integer cachePackageTagsStore) {
        this.cachePackageTagsStore = cachePackageTagsStore;
    }
    
    /**
     * Set value of mailHostOverride
     *
     * @param mailHostOverride
     */
    public final void setMailHostOverride(final String mailHostOverride) {
        this.mailHostOverride = mailHostOverride;
    }
    
    /**
     * Set value of dataStoreConnUsageLimit
     *
     * @param dataStoreConnUsageLimit
     */
    public final void setDataStoreConnUsageLimit(final Integer dataStoreConnUsageLimit) {
        this.dataStoreConnUsageLimit = dataStoreConnUsageLimit;
    }
    
    /**
     * Set value of logMaxSize
     *
     * @param logMaxSize
     */
    public final void setLogMaxSize(final String logMaxSize) {
        this.logMaxSize = logMaxSize;
    }
    
    /**
     * Set value of useJSP
     *
     * @param useJSP
     */
    public final void setUseJSP(final Boolean useJSP) {
        this.useJSP = useJSP;
    }
    
    /**
     * Set value of dataStoreUrl
     *
     * @param dataStoreUrl
     */
    public final void setDataStoreUrl(final String dataStoreUrl) {
        this.dataStoreUrl = dataStoreUrl;
    }
    
    /**
     * Set value of templatePath
     *
     * @param templatePath
     */
    public final void setTemplatePath(final String templatePath) {
        this.templatePath = templatePath;
    }
    
    /**
     * Set value of cacheTemplatesStore
     *
     * @param cacheTemplatesStore
     */
    public final void setCacheTemplatesStore(final Integer cacheTemplatesStore) {
        this.cacheTemplatesStore = cacheTemplatesStore;
    }
    
    /**
     * Set value of removeTemplateCache
     *
     * @param removeTemplateCache
     */
    public final void setRemoveTemplateCache(final String removeTemplateCache) {
        this.removeTemplateCache = removeTemplateCache;
    }
    
    /**
     * Set value of jspListTemplate
     *
     * @param jspListTemplate
     */
    public final void setJspListTemplate(final String jspListTemplate) {
        this.jspListTemplate = jspListTemplate;
    }
    
    /**
     * Set value of removePageCache
     *
     * @param removePageCache
     */
    public final void setRemovePageCache(final String removePageCache) {
        this.removePageCache = removePageCache;
    }
    
    /**
     * Set value of adminGroupID
     *
     * @param adminGroupID
     */
    public final void setAdminGroupID(final Integer adminGroupID) {
        this.adminGroupID = adminGroupID;
    }
    
    /**
     * Set value of maxUrlLength
     *
     * @param maxUrlLength
     */
    public final void setMaxUrlLength(final Integer maxUrlLength) {
        this.maxUrlLength = maxUrlLength;
    }
    
    /**
     * Set value of cachePagesRefresh
     *
     * @param cachePagesRefresh
     */
    public final void setCachePagesRefresh(final Integer cachePagesRefresh) {
        this.cachePagesRefresh = cachePagesRefresh;
    }
    
    /**
     * Set value of dataStoreDriver
     *
     * @param dataStoreDriver
     */
    public final void setDataStoreDriver(final String dataStoreDriver) {
        this.dataStoreDriver = dataStoreDriver;
    }
    
    /**
     * Set value of dataStoreUser
     *
     * @param dataStoreUser
     */
    public final void setDataStoreUser(final String dataStoreUser) {
        this.dataStoreUser = dataStoreUser;
    }
    
    /**
     * Set value of defaultListTemplate
     *
     * @param defaultListTemplate
     */
    public final void setDefaultListTemplate(final String defaultListTemplate) {
        this.defaultListTemplate = defaultListTemplate;
    }
}