package aka.convertor.examples.example2;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class InitParam {

    private Integer cachePackageTagsTrack;
    @SerializedName("configGlossary:staticPath")
    private String configGlossaryStaticPath;
    @SerializedName("configGlossary:installationAt")
    private String configGlossaryInstallationAt;
    private Integer cacheTemplatesTrack;
    @SerializedName("configGlossary:poweredBy")
    private String configGlossaryPoweredBy;
    private String searchEngineFileTemplate;
    private String templateProcessorClass;
    private String searchEngineListTemplate;
    private Boolean useDataStore;
    private Boolean betaServer;
    private String templateLoaderClass;
    private String searchEngineRobotsDb;
    private String logLocation;
    private String mailHost;
    private Integer cachePackageTagsRefresh;
    private String dataStoreLogLevel;
    private String fileTransferFolder;
    private String dataStoreTestQuery;
    private Integer lookInContext;
    private Integer dataStoreMaxConns;
    private String dataStoreName;
    private String templateOverridePath;
    private String dataStoreLogFile;
    private Integer dataStoreInitConns;
    private Integer dataLog;
    private String redirectionClass;
    private String jspFileTemplate;
    private Integer cacheTemplatesRefresh;
    private String dataStorePassword;
    private String dataStoreClass;
    private Integer log;
    private String defaultFileTemplate;
    private String dataLogLocation;
    @SerializedName("configGlossary:adminEmail")
    private String configGlossaryAdminEmail;
    private Integer cachePagesStore;
    @SerializedName("configGlossary:poweredByIcon")
    private String configGlossaryPoweredByIcon;
    private Integer cachePagesTrack;
    private Integer cachePagesDirtyRead;
    private String dataLogMaxSize;
    private Integer cachePackageTagsStore;
    private String mailHostOverride;
    private Integer dataStoreConnUsageLimit;
    private String logMaxSize;
    private Boolean useJSP;
    private String dataStoreUrl;
    private String templatePath;
    private Integer cacheTemplatesStore;
    private String removeTemplateCache;
    private String jspListTemplate;
    private String removePageCache;
    private Integer adminGroupID;
    private Integer maxUrlLength;
    private Integer cachePagesRefresh;
    private String dataStoreDriver;
    private String dataStoreUser;
    private String defaultListTemplate;

    /**
     * Get value of cachePackageTagsTrack 
     *
     * @return Integer value of cachePackageTagsTrack
     */
    public Integer getCachePackageTagsTrack() {
       return this.cachePackageTagsTrack;
    }

    /**
     * Get value of configGlossaryStaticPath 
     *
     * @return String value of configGlossaryStaticPath
     */
    public String getConfigGlossaryStaticPath() {
       return this.configGlossaryStaticPath;
    }

    /**
     * Get value of configGlossaryInstallationAt 
     *
     * @return String value of configGlossaryInstallationAt
     */
    public String getConfigGlossaryInstallationAt() {
       return this.configGlossaryInstallationAt;
    }

    /**
     * Get value of cacheTemplatesTrack 
     *
     * @return Integer value of cacheTemplatesTrack
     */
    public Integer getCacheTemplatesTrack() {
       return this.cacheTemplatesTrack;
    }

    /**
     * Get value of configGlossaryPoweredBy 
     *
     * @return String value of configGlossaryPoweredBy
     */
    public String getConfigGlossaryPoweredBy() {
       return this.configGlossaryPoweredBy;
    }

    /**
     * Get value of searchEngineFileTemplate 
     *
     * @return String value of searchEngineFileTemplate
     */
    public String getSearchEngineFileTemplate() {
       return this.searchEngineFileTemplate;
    }

    /**
     * Get value of templateProcessorClass 
     *
     * @return String value of templateProcessorClass
     */
    public String getTemplateProcessorClass() {
       return this.templateProcessorClass;
    }

    /**
     * Get value of searchEngineListTemplate 
     *
     * @return String value of searchEngineListTemplate
     */
    public String getSearchEngineListTemplate() {
       return this.searchEngineListTemplate;
    }

    /**
     * Get value of useDataStore 
     *
     * @return Boolean value of useDataStore
     */
    public Boolean getUseDataStore() {
       return this.useDataStore;
    }

    /**
     * Get value of betaServer 
     *
     * @return Boolean value of betaServer
     */
    public Boolean getBetaServer() {
       return this.betaServer;
    }

    /**
     * Get value of templateLoaderClass 
     *
     * @return String value of templateLoaderClass
     */
    public String getTemplateLoaderClass() {
       return this.templateLoaderClass;
    }

    /**
     * Get value of searchEngineRobotsDb 
     *
     * @return String value of searchEngineRobotsDb
     */
    public String getSearchEngineRobotsDb() {
       return this.searchEngineRobotsDb;
    }

    /**
     * Get value of logLocation 
     *
     * @return String value of logLocation
     */
    public String getLogLocation() {
       return this.logLocation;
    }

    /**
     * Get value of mailHost 
     *
     * @return String value of mailHost
     */
    public String getMailHost() {
       return this.mailHost;
    }

    /**
     * Get value of cachePackageTagsRefresh 
     *
     * @return Integer value of cachePackageTagsRefresh
     */
    public Integer getCachePackageTagsRefresh() {
       return this.cachePackageTagsRefresh;
    }

    /**
     * Get value of dataStoreLogLevel 
     *
     * @return String value of dataStoreLogLevel
     */
    public String getDataStoreLogLevel() {
       return this.dataStoreLogLevel;
    }

    /**
     * Get value of fileTransferFolder 
     *
     * @return String value of fileTransferFolder
     */
    public String getFileTransferFolder() {
       return this.fileTransferFolder;
    }

    /**
     * Get value of dataStoreTestQuery 
     *
     * @return String value of dataStoreTestQuery
     */
    public String getDataStoreTestQuery() {
       return this.dataStoreTestQuery;
    }

    /**
     * Get value of lookInContext 
     *
     * @return Integer value of lookInContext
     */
    public Integer getLookInContext() {
       return this.lookInContext;
    }

    /**
     * Get value of dataStoreMaxConns 
     *
     * @return Integer value of dataStoreMaxConns
     */
    public Integer getDataStoreMaxConns() {
       return this.dataStoreMaxConns;
    }

    /**
     * Get value of dataStoreName 
     *
     * @return String value of dataStoreName
     */
    public String getDataStoreName() {
       return this.dataStoreName;
    }

    /**
     * Get value of templateOverridePath 
     *
     * @return String value of templateOverridePath
     */
    public String getTemplateOverridePath() {
       return this.templateOverridePath;
    }

    /**
     * Get value of dataStoreLogFile 
     *
     * @return String value of dataStoreLogFile
     */
    public String getDataStoreLogFile() {
       return this.dataStoreLogFile;
    }

    /**
     * Get value of dataStoreInitConns 
     *
     * @return Integer value of dataStoreInitConns
     */
    public Integer getDataStoreInitConns() {
       return this.dataStoreInitConns;
    }

    /**
     * Get value of dataLog 
     *
     * @return Integer value of dataLog
     */
    public Integer getDataLog() {
       return this.dataLog;
    }

    /**
     * Get value of redirectionClass 
     *
     * @return String value of redirectionClass
     */
    public String getRedirectionClass() {
       return this.redirectionClass;
    }

    /**
     * Get value of jspFileTemplate 
     *
     * @return String value of jspFileTemplate
     */
    public String getJspFileTemplate() {
       return this.jspFileTemplate;
    }

    /**
     * Get value of cacheTemplatesRefresh 
     *
     * @return Integer value of cacheTemplatesRefresh
     */
    public Integer getCacheTemplatesRefresh() {
       return this.cacheTemplatesRefresh;
    }

    /**
     * Get value of dataStorePassword 
     *
     * @return String value of dataStorePassword
     */
    public String getDataStorePassword() {
       return this.dataStorePassword;
    }

    /**
     * Get value of dataStoreClass 
     *
     * @return String value of dataStoreClass
     */
    public String getDataStoreClass() {
       return this.dataStoreClass;
    }

    /**
     * Get value of log 
     *
     * @return Integer value of log
     */
    public Integer getLog() {
       return this.log;
    }

    /**
     * Get value of defaultFileTemplate 
     *
     * @return String value of defaultFileTemplate
     */
    public String getDefaultFileTemplate() {
       return this.defaultFileTemplate;
    }

    /**
     * Get value of dataLogLocation 
     *
     * @return String value of dataLogLocation
     */
    public String getDataLogLocation() {
       return this.dataLogLocation;
    }

    /**
     * Get value of configGlossaryAdminEmail 
     *
     * @return String value of configGlossaryAdminEmail
     */
    public String getConfigGlossaryAdminEmail() {
       return this.configGlossaryAdminEmail;
    }

    /**
     * Get value of cachePagesStore 
     *
     * @return Integer value of cachePagesStore
     */
    public Integer getCachePagesStore() {
       return this.cachePagesStore;
    }

    /**
     * Get value of configGlossaryPoweredByIcon 
     *
     * @return String value of configGlossaryPoweredByIcon
     */
    public String getConfigGlossaryPoweredByIcon() {
       return this.configGlossaryPoweredByIcon;
    }

    /**
     * Get value of cachePagesTrack 
     *
     * @return Integer value of cachePagesTrack
     */
    public Integer getCachePagesTrack() {
       return this.cachePagesTrack;
    }

    /**
     * Get value of cachePagesDirtyRead 
     *
     * @return Integer value of cachePagesDirtyRead
     */
    public Integer getCachePagesDirtyRead() {
       return this.cachePagesDirtyRead;
    }

    /**
     * Get value of dataLogMaxSize 
     *
     * @return String value of dataLogMaxSize
     */
    public String getDataLogMaxSize() {
       return this.dataLogMaxSize;
    }

    /**
     * Get value of cachePackageTagsStore 
     *
     * @return Integer value of cachePackageTagsStore
     */
    public Integer getCachePackageTagsStore() {
       return this.cachePackageTagsStore;
    }

    /**
     * Get value of mailHostOverride 
     *
     * @return String value of mailHostOverride
     */
    public String getMailHostOverride() {
       return this.mailHostOverride;
    }

    /**
     * Get value of dataStoreConnUsageLimit 
     *
     * @return Integer value of dataStoreConnUsageLimit
     */
    public Integer getDataStoreConnUsageLimit() {
       return this.dataStoreConnUsageLimit;
    }

    /**
     * Get value of logMaxSize 
     *
     * @return String value of logMaxSize
     */
    public String getLogMaxSize() {
       return this.logMaxSize;
    }

    /**
     * Get value of useJSP 
     *
     * @return Boolean value of useJSP
     */
    public Boolean getUseJSP() {
       return this.useJSP;
    }

    /**
     * Get value of dataStoreUrl 
     *
     * @return String value of dataStoreUrl
     */
    public String getDataStoreUrl() {
       return this.dataStoreUrl;
    }

    /**
     * Get value of templatePath 
     *
     * @return String value of templatePath
     */
    public String getTemplatePath() {
       return this.templatePath;
    }

    /**
     * Get value of cacheTemplatesStore 
     *
     * @return Integer value of cacheTemplatesStore
     */
    public Integer getCacheTemplatesStore() {
       return this.cacheTemplatesStore;
    }

    /**
     * Get value of removeTemplateCache 
     *
     * @return String value of removeTemplateCache
     */
    public String getRemoveTemplateCache() {
       return this.removeTemplateCache;
    }

    /**
     * Get value of jspListTemplate 
     *
     * @return String value of jspListTemplate
     */
    public String getJspListTemplate() {
       return this.jspListTemplate;
    }

    /**
     * Get value of removePageCache 
     *
     * @return String value of removePageCache
     */
    public String getRemovePageCache() {
       return this.removePageCache;
    }

    /**
     * Get value of adminGroupID 
     *
     * @return Integer value of adminGroupID
     */
    public Integer getAdminGroupID() {
       return this.adminGroupID;
    }

    /**
     * Get value of maxUrlLength 
     *
     * @return Integer value of maxUrlLength
     */
    public Integer getMaxUrlLength() {
       return this.maxUrlLength;
    }

    /**
     * Get value of cachePagesRefresh 
     *
     * @return Integer value of cachePagesRefresh
     */
    public Integer getCachePagesRefresh() {
       return this.cachePagesRefresh;
    }

    /**
     * Get value of dataStoreDriver 
     *
     * @return String value of dataStoreDriver
     */
    public String getDataStoreDriver() {
       return this.dataStoreDriver;
    }

    /**
     * Get value of dataStoreUser 
     *
     * @return String value of dataStoreUser
     */
    public String getDataStoreUser() {
       return this.dataStoreUser;
    }

    /**
     * Get value of defaultListTemplate 
     *
     * @return String value of defaultListTemplate
     */
    public String getDefaultListTemplate() {
       return this.defaultListTemplate;
    }
}
