package aka.convertor.examples.example2;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class Servlet {

    @JsonProperty("init-param")
    private InitParam initParam;
    @JsonProperty("servlet-name")
    private String servletName;
    @JsonProperty("servlet-class")
    private String servletClass;

    /**
     * Filling Constructor
     *
     * @param initParam InitParam
     * @param servletName String
     * @param servletClass String
     */
    public Servlet(final InitParam initParam, final String servletName, final String servletClass) {
        this.initParam = initParam;
        this.servletName = servletName;
        this.servletClass = servletClass;
    }
    
    /**
     * Get value of initParam
     *
     * @return InitParam value of initParam
     */
    public final InitParam getInitParam() {
        return this.initParam;
    }
    
    /**
     * Get value of servletName
     *
     * @return String value of servletName
     */
    public final String getServletName() {
        return this.servletName;
    }
    
    /**
     * Get value of servletClass
     *
     * @return String value of servletClass
     */
    public final String getServletClass() {
        return this.servletClass;
    }

    
    /**
     * Set value of initParam
     *
     * @param initParam
     */
    public final void setInitParam(final InitParam initParam) {
        this.initParam = initParam;
    }
    
    /**
     * Set value of servletName
     *
     * @param servletName
     */
    public final void setServletName(final String servletName) {
        this.servletName = servletName;
    }
    
    /**
     * Set value of servletClass
     *
     * @param servletClass
     */
    public final void setServletClass(final String servletClass) {
        this.servletClass = servletClass;
    }
}