package aka.convertor.examples.example2;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class ServletMapping {

    private String cofaxAdmin;
    private String cofaxCDS;
    private String cofaxEmail;
    private String fileServlet;
    private String cofaxTools;

    /**
     * Get value of cofaxAdmin 
     *
     * @return String value of cofaxAdmin
     */
    public String getCofaxAdmin() {
       return this.cofaxAdmin;
    }

    /**
     * Get value of cofaxCDS 
     *
     * @return String value of cofaxCDS
     */
    public String getCofaxCDS() {
       return this.cofaxCDS;
    }

    /**
     * Get value of cofaxEmail 
     *
     * @return String value of cofaxEmail
     */
    public String getCofaxEmail() {
       return this.cofaxEmail;
    }

    /**
     * Get value of fileServlet 
     *
     * @return String value of fileServlet
     */
    public String getFileServlet() {
       return this.fileServlet;
    }

    /**
     * Get value of cofaxTools 
     *
     * @return String value of cofaxTools
     */
    public String getCofaxTools() {
       return this.cofaxTools;
    }
}
