package aka.convertor.examples.example2;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class ServletMapping {

    private String cofaxAdmin;
    private String cofaxCDS;
    private String cofaxEmail;
    private String fileServlet;
    private String cofaxTools;

    /**
     * Filling Constructor
     *
     * @param cofaxAdmin String
     * @param cofaxCDS String
     * @param cofaxEmail String
     * @param fileServlet String
     * @param cofaxTools String
     */
    public ServletMapping(final String cofaxAdmin, final String cofaxCDS, final String cofaxEmail, final String fileServlet, final String cofaxTools) {
        this.cofaxAdmin = cofaxAdmin;
        this.cofaxCDS = cofaxCDS;
        this.cofaxEmail = cofaxEmail;
        this.fileServlet = fileServlet;
        this.cofaxTools = cofaxTools;
    }
    
    /**
     * Get value of cofaxAdmin
     *
     * @return String value of cofaxAdmin
     */
    public final String getCofaxAdmin() {
        return this.cofaxAdmin;
    }
    
    /**
     * Get value of cofaxCDS
     *
     * @return String value of cofaxCDS
     */
    public final String getCofaxCDS() {
        return this.cofaxCDS;
    }
    
    /**
     * Get value of cofaxEmail
     *
     * @return String value of cofaxEmail
     */
    public final String getCofaxEmail() {
        return this.cofaxEmail;
    }
    
    /**
     * Get value of fileServlet
     *
     * @return String value of fileServlet
     */
    public final String getFileServlet() {
        return this.fileServlet;
    }
    
    /**
     * Get value of cofaxTools
     *
     * @return String value of cofaxTools
     */
    public final String getCofaxTools() {
        return this.cofaxTools;
    }

    
    /**
     * Set value of cofaxAdmin
     *
     * @param cofaxAdmin
     */
    public final void setCofaxAdmin(final String cofaxAdmin) {
        this.cofaxAdmin = cofaxAdmin;
    }
    
    /**
     * Set value of cofaxCDS
     *
     * @param cofaxCDS
     */
    public final void setCofaxCDS(final String cofaxCDS) {
        this.cofaxCDS = cofaxCDS;
    }
    
    /**
     * Set value of cofaxEmail
     *
     * @param cofaxEmail
     */
    public final void setCofaxEmail(final String cofaxEmail) {
        this.cofaxEmail = cofaxEmail;
    }
    
    /**
     * Set value of fileServlet
     *
     * @param fileServlet
     */
    public final void setFileServlet(final String fileServlet) {
        this.fileServlet = fileServlet;
    }
    
    /**
     * Set value of cofaxTools
     *
     * @param cofaxTools
     */
    public final void setCofaxTools(final String cofaxTools) {
        this.cofaxTools = cofaxTools;
    }
}