package aka.convertor.examples.example2;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class Servlet {

    @SerializedName("init-param")
    private InitParam initParam;
    @SerializedName("servlet-name")
    private String servletName;
    @SerializedName("servlet-class")
    private String servletClass;

    /**
     * Get value of initParam 
     *
     * @return InitParam value of initParam
     */
    public InitParam getInitParam() {
       return this.initParam;
    }

    /**
     * Get value of servletName 
     *
     * @return String value of servletName
     */
    public String getServletName() {
       return this.servletName;
    }

    /**
     * Get value of servletClass 
     *
     * @return String value of servletClass
     */
    public String getServletClass() {
       return this.servletClass;
    }
}
