package aka.convertor.examples.example2;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class Taglib {

    @JsonProperty("taglib-location")
    private String taglibLocation;
    @JsonProperty("taglib-uri")
    private String taglibUri;

    /**
     * Filling Constructor
     *
     * @param taglibLocation String
     * @param taglibUri String
     */
    public Taglib(final String taglibLocation, final String taglibUri) {
        this.taglibLocation = taglibLocation;
        this.taglibUri = taglibUri;
    }
    
    /**
     * Get value of taglibLocation
     *
     * @return String value of taglibLocation
     */
    public final String getTaglibLocation() {
        return this.taglibLocation;
    }
    
    /**
     * Get value of taglibUri
     *
     * @return String value of taglibUri
     */
    public final String getTaglibUri() {
        return this.taglibUri;
    }

    
    /**
     * Set value of taglibLocation
     *
     * @param taglibLocation
     */
    public final void setTaglibLocation(final String taglibLocation) {
        this.taglibLocation = taglibLocation;
    }
    
    /**
     * Set value of taglibUri
     *
     * @param taglibUri
     */
    public final void setTaglibUri(final String taglibUri) {
        this.taglibUri = taglibUri;
    }
}