package aka.convertor.examples.example2;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class Taglib {

    @SerializedName("taglib-location")
    private String taglibLocation;
    @SerializedName("taglib-uri")
    private String taglibUri;

    /**
     * Get value of taglibLocation 
     *
     * @return String value of taglibLocation
     */
    public String getTaglibLocation() {
       return this.taglibLocation;
    }

    /**
     * Get value of taglibUri 
     *
     * @return String value of taglibUri
     */
    public String getTaglibUri() {
       return this.taglibUri;
    }
}
