package aka.convertor.examples.example2;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class WebApp {

    @SerializedName("servlet-mapping")
    private ServletMapping servletMapping;
    private Taglib taglib;
    private List<Servlet> servlet;

    /**
     * Get value of servletMapping 
     *
     * @return ServletMapping value of servletMapping
     */
    public ServletMapping getServletMapping() {
       return this.servletMapping;
    }

    /**
     * Get value of taglib 
     *
     * @return Taglib value of taglib
     */
    public Taglib getTaglib() {
       return this.taglib;
    }

    /**
     * Get value of servlet 
     *
     * @return List<Servlet> value of servlet
     */
    public List<Servlet> getServlet() {
       return this.servlet;
    }
}
