package aka.convertor.examples.example2;


import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class WebApp {

    @JsonProperty("servlet-mapping")
    private ServletMapping servletMapping;
    private Taglib taglib;
    private List<Servlet> servlet = new ArrayList<>();

    /**
     * Filling Constructor
     *
     * @param servletMapping ServletMapping
     * @param taglib Taglib
     * @param servlet List<Servlet
     */
    public WebApp(final ServletMapping servletMapping, final Taglib taglib, final List<Servlet> servlet) {
        this.servletMapping = servletMapping;
        this.taglib = taglib;
        this.servlet = servlet;
    }
    
    /**
     * Get value of servletMapping
     *
     * @return ServletMapping value of servletMapping
     */
    public final ServletMapping getServletMapping() {
        return this.servletMapping;
    }
    
    /**
     * Get value of taglib
     *
     * @return Taglib value of taglib
     */
    public final Taglib getTaglib() {
        return this.taglib;
    }
    
    /**
     * Get value of servlet
     *
     * @return List<Servlet> value of servlet
     */
    public final List<Servlet> getServlet() {
        return this.servlet;
    }

    
    /**
     * Set value of servletMapping
     *
     * @param servletMapping
     */
    public final void setServletMapping(final ServletMapping servletMapping) {
        this.servletMapping = servletMapping;
    }
    
    /**
     * Set value of taglib
     *
     * @param taglib
     */
    public final void setTaglib(final Taglib taglib) {
        this.taglib = taglib;
    }
    
    /**
     * Set value of servlet
     *
     * @param servlet
     */
    public final void getServlet(final List<Servlet> servlet) {
        this.servlet = servlet;
    }
}