package ${package};

import com.google.gson.annotations.SerializedName;
#if( $comp.ContainList == "true" )
import java.util.List;
#end

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class ${comp.name} {

#foreach( $column in $comp.Nodes ) 
#if (${column.SerName} != ${column.Name})
    @SerializedName("${column.SerName}")
#end
#if ( $column.Type == "List" )
    private List<${column.Subtype}> ${column.Name};
#elseif ( $column.Type == "java.util.Date" )
    private String ${column.Name};
#else
    private ${column.Type} ${column.Name};
#end
#end

#foreach( $column in $comp.Nodes ) 
    /**
     * Get value of ${column.Name}
#if ( $column.Type == "List" )     
     * @return List<${column.Subtype}> value of ${column.Name}
     */
    public List<${column.Subtype}> get${util.firstLetterUpperCase( $column.Name )}() {
#elseif ( $column.Type == "java.util.Date" )
     * @return String value of ${column.Name}
     */
    public String get${util.firstLetterUpperCase( $column.Name )}() {
#else 
    * @return ${column.Type} value of ${column.Name}
     */
    public ${column.Type} get${util.firstLetterUpperCase( $column.Name )}() {
#end
        return this.${column.Name};
    }
#end

}