package ${package};

import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
 
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;

/**
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
public final class ${deserialiser.Name}Deserializer extends JsonDeserializer<Date> {

    @Override
    public final Date deserialize(final JsonParser jsonparser, final DeserializationContext deserializationcontext) throws IOException, JsonProcessingException {
        final SimpleDateFormat format = new SimpleDateFormat("${deserialiser.Format}");
        final String date = jsonparser.getText();
        try {
            return format.parse(date);
        } catch (final ParseException e) {
            // nothing to do
        }

        return null;
    }
}