package aka.convertor.examples.example1;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class Example1 {

    private Glossary glossary;

    /**
     * Get value of glossary 
     *
     * @return Glossary value of glossary
     */
    public Glossary getGlossary() {
       return this.glossary;
    }
}
