package aka.convertor.examples.example1;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class Example1 {

    private Glossary glossary;

    /**
     * Filling Constructor
     *
     * @param glossary Glossary
     */
    public Example1(final Glossary glossary) {
        this.glossary = glossary;
    }
    
    /**
     * Get value of glossary
     *
     * @return Glossary value of glossary
     */
    public final Glossary getGlossary() {
        return this.glossary;
    }

    
    /**
     * Set value of glossary
     *
     * @param glossary
     */
    public final void setGlossary(final Glossary glossary) {
        this.glossary = glossary;
    }
}