package aka.convertor.examples.example1;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class GlossDiv {

    @JsonProperty("GlossList")
    private GlossList glossList;
    private String title;

    /**
     * Filling Constructor
     *
     * @param glossList GlossList
     * @param title String
     */
    public GlossDiv(final GlossList glossList, final String title) {
        this.glossList = glossList;
        this.title = title;
    }
    
    /**
     * Get value of glossList
     *
     * @return GlossList value of glossList
     */
    public final GlossList getGlossList() {
        return this.glossList;
    }
    
    /**
     * Get value of title
     *
     * @return String value of title
     */
    public final String getTitle() {
        return this.title;
    }

    
    /**
     * Set value of glossList
     *
     * @param glossList
     */
    public final void setGlossList(final GlossList glossList) {
        this.glossList = glossList;
    }
    
    /**
     * Set value of title
     *
     * @param title
     */
    public final void setTitle(final String title) {
        this.title = title;
    }
}