package aka.convertor.examples.example1;


import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class GlossDef {

    private String para;
    @JsonProperty("GlossSeeAlso")
    private List<String> glossSeeAlso = new ArrayList<>();

    /**
     * Filling Constructor
     *
     * @param para String
     * @param glossSeeAlso List<String
     */
    public GlossDef(final String para, final List<String> glossSeeAlso) {
        this.para = para;
        this.glossSeeAlso = glossSeeAlso;
    }
    
    /**
     * Get value of para
     *
     * @return String value of para
     */
    public final String getPara() {
        return this.para;
    }
    
    /**
     * Get value of glossSeeAlso
     *
     * @return List<String> value of glossSeeAlso
     */
    public final List<String> getGlossSeeAlso() {
        return this.glossSeeAlso;
    }

    
    /**
     * Set value of para
     *
     * @param para
     */
    public final void setPara(final String para) {
        this.para = para;
    }
    
    /**
     * Set value of glossSeeAlso
     *
     * @param glossSeeAlso
     */
    public final void getGlossSeeAlso(final List<String> glossSeeAlso) {
        this.glossSeeAlso = glossSeeAlso;
    }
}