package aka.convertor.examples.example1;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class Glossary {

    private String title;
    @JsonProperty("GlossDiv")
    private GlossDiv glossDiv;

    /**
     * Filling Constructor
     *
     * @param title String
     * @param glossDiv GlossDiv
     */
    public Glossary(final String title, final GlossDiv glossDiv) {
        this.title = title;
        this.glossDiv = glossDiv;
    }
    
    /**
     * Get value of title
     *
     * @return String value of title
     */
    public final String getTitle() {
        return this.title;
    }
    
    /**
     * Get value of glossDiv
     *
     * @return GlossDiv value of glossDiv
     */
    public final GlossDiv getGlossDiv() {
        return this.glossDiv;
    }

    
    /**
     * Set value of title
     *
     * @param title
     */
    public final void setTitle(final String title) {
        this.title = title;
    }
    
    /**
     * Set value of glossDiv
     *
     * @param glossDiv
     */
    public final void setGlossDiv(final GlossDiv glossDiv) {
        this.glossDiv = glossDiv;
    }
}