package aka.convertor.examples.example1;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class GlossEntry {

    @JsonProperty("GlossTerm")
    private String glossTerm;
    @JsonProperty("GlossSee")
    private String glossSee;
    @JsonProperty("SortAs")
    private String sortAs;
    @JsonProperty("GlossDef")
    private GlossDef glossDef;
    @JsonProperty("ID")
    private String iD;
    @JsonProperty("Acronym")
    private String acronym;
    @JsonProperty("Abbrev")
    private String abbrev;

    /**
     * Filling Constructor
     *
     * @param glossTerm String
     * @param glossSee String
     * @param sortAs String
     * @param glossDef GlossDef
     * @param iD String
     * @param acronym String
     * @param abbrev String
     */
    public GlossEntry(final String glossTerm, final String glossSee, final String sortAs, final GlossDef glossDef, final String iD, final String acronym, final String abbrev) {
        this.glossTerm = glossTerm;
        this.glossSee = glossSee;
        this.sortAs = sortAs;
        this.glossDef = glossDef;
        this.iD = iD;
        this.acronym = acronym;
        this.abbrev = abbrev;
    }
    
    /**
     * Get value of glossTerm
     *
     * @return String value of glossTerm
     */
    public final String getGlossTerm() {
        return this.glossTerm;
    }
    
    /**
     * Get value of glossSee
     *
     * @return String value of glossSee
     */
    public final String getGlossSee() {
        return this.glossSee;
    }
    
    /**
     * Get value of sortAs
     *
     * @return String value of sortAs
     */
    public final String getSortAs() {
        return this.sortAs;
    }
    
    /**
     * Get value of glossDef
     *
     * @return GlossDef value of glossDef
     */
    public final GlossDef getGlossDef() {
        return this.glossDef;
    }
    
    /**
     * Get value of iD
     *
     * @return String value of iD
     */
    public final String getID() {
        return this.iD;
    }
    
    /**
     * Get value of acronym
     *
     * @return String value of acronym
     */
    public final String getAcronym() {
        return this.acronym;
    }
    
    /**
     * Get value of abbrev
     *
     * @return String value of abbrev
     */
    public final String getAbbrev() {
        return this.abbrev;
    }

    
    /**
     * Set value of glossTerm
     *
     * @param glossTerm
     */
    public final void setGlossTerm(final String glossTerm) {
        this.glossTerm = glossTerm;
    }
    
    /**
     * Set value of glossSee
     *
     * @param glossSee
     */
    public final void setGlossSee(final String glossSee) {
        this.glossSee = glossSee;
    }
    
    /**
     * Set value of sortAs
     *
     * @param sortAs
     */
    public final void setSortAs(final String sortAs) {
        this.sortAs = sortAs;
    }
    
    /**
     * Set value of glossDef
     *
     * @param glossDef
     */
    public final void setGlossDef(final GlossDef glossDef) {
        this.glossDef = glossDef;
    }
    
    /**
     * Set value of iD
     *
     * @param iD
     */
    public final void setID(final String iD) {
        this.iD = iD;
    }
    
    /**
     * Set value of acronym
     *
     * @param acronym
     */
    public final void setAcronym(final String acronym) {
        this.acronym = acronym;
    }
    
    /**
     * Set value of abbrev
     *
     * @param abbrev
     */
    public final void setAbbrev(final String abbrev) {
        this.abbrev = abbrev;
    }
}