package aka.convertor.examples.example1;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class Glossary {

    private String title;
    @SerializedName("GlossDiv")
    private GlossDiv glossDiv;

    /**
     * Get value of title 
     *
     * @return String value of title
     */
    public String getTitle() {
       return this.title;
    }

    /**
     * Get value of glossDiv 
     *
     * @return GlossDiv value of glossDiv
     */
    public GlossDiv getGlossDiv() {
       return this.glossDiv;
    }
}
