package aka.convertor.examples.example1;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class GlossDiv {

    @SerializedName("GlossList")
    private GlossList glossList;
    private String title;

    /**
     * Get value of glossList 
     *
     * @return GlossList value of glossList
     */
    public GlossList getGlossList() {
       return this.glossList;
    }

    /**
     * Get value of title 
     *
     * @return String value of title
     */
    public String getTitle() {
       return this.title;
    }
}
