package aka.convertor.examples.example1;


import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Simple pojo 
 *
 * Generated by JetTools, do not edit this file directly.
 * 
 * @author JetToolsFramework
 */ 
@JsonIgnoreProperties(ignoreUnknown = true) 
public final class GlossList {

    @JsonProperty("GlossEntry")
    private GlossEntry glossEntry;

    /**
     * Filling Constructor
     *
     * @param glossEntry GlossEntry
     */
    public GlossList(final GlossEntry glossEntry) {
        this.glossEntry = glossEntry;
    }
    
    /**
     * Get value of glossEntry
     *
     * @return GlossEntry value of glossEntry
     */
    public final GlossEntry getGlossEntry() {
        return this.glossEntry;
    }

    
    /**
     * Set value of glossEntry
     *
     * @param glossEntry
     */
    public final void setGlossEntry(final GlossEntry glossEntry) {
        this.glossEntry = glossEntry;
    }
}