package aka.convertor.examples.example1;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class GlossDef {

    private String para;
    @SerializedName("GlossSeeAlso")
    private List<String> glossSeeAlso;

    /**
     * Get value of para 
     *
     * @return String value of para
     */
    public String getPara() {
       return this.para;
    }

    /**
     * Get value of glossSeeAlso 
     *
     * @return List<String> value of glossSeeAlso
     */
    public List<String> getGlossSeeAlso() {
       return this.glossSeeAlso;
    }
}
