package aka.convertor.examples.example1;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class GlossList {

    @SerializedName("GlossEntry")
    private GlossEntry glossEntry;

    /**
     * Get value of glossEntry 
     *
     * @return GlossEntry value of glossEntry
     */
    public GlossEntry getGlossEntry() {
       return this.glossEntry;
    }
}
