package aka.convertor.examples.example1;

import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Simple pojo for parsing Json with Gson library
 *
 * Generated by JSonPojo, do not edit this file directly.
 * 
 * @author Welle Charlotte
 */
public final class GlossEntry {

    @SerializedName("GlossTerm")
    private String glossTerm;
    @SerializedName("GlossSee")
    private String glossSee;
    @SerializedName("SortAs")
    private String sortAs;
    @SerializedName("GlossDef")
    private GlossDef glossDef;
    @SerializedName("ID")
    private String iD;
    @SerializedName("Acronym")
    private String acronym;
    @SerializedName("Abbrev")
    private String abbrev;

    /**
     * Get value of glossTerm 
     *
     * @return String value of glossTerm
     */
    public String getGlossTerm() {
       return this.glossTerm;
    }

    /**
     * Get value of glossSee 
     *
     * @return String value of glossSee
     */
    public String getGlossSee() {
       return this.glossSee;
    }

    /**
     * Get value of sortAs 
     *
     * @return String value of sortAs
     */
    public String getSortAs() {
       return this.sortAs;
    }

    /**
     * Get value of glossDef 
     *
     * @return GlossDef value of glossDef
     */
    public GlossDef getGlossDef() {
       return this.glossDef;
    }

    /**
     * Get value of iD 
     *
     * @return String value of iD
     */
    public String getID() {
       return this.iD;
    }

    /**
     * Get value of acronym 
     *
     * @return String value of acronym
     */
    public String getAcronym() {
       return this.acronym;
    }

    /**
     * Get value of abbrev 
     *
     * @return String value of abbrev
     */
    public String getAbbrev() {
       return this.abbrev;
    }
}
